version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: martinjsdev/next-movie:latest
    ports:
      - "3000:3000"
    env_file:
      - ./.env 
    restart: unless-stopped
