name: Continuous Deployment 

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        ports:
          - 2375:2375
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          cd next-movie
          npm install

      - name: Build the Next.js application
        run: |
          cd next-movie
          npm run build

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with Docker Compose
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          cd next-movie
          docker-compose -f docker-compose.yml build

      - name: Push Docker image
        run: |
          cd next-movie

          # Tagging the image with the commit SHA and latest
          docker tag martinjsdev/next-movie:latest martinjsdev/next-movie:${{ github.sha }}
          docker tag martinjsdev/next-movie:${{ github.sha }} martinjsdev/next-movie:latest

          # Push both the SHA tag and latest tag
          docker push martinjsdev/next-movie:${{ github.sha }}
          docker push martinjsdev/next-movie:latest
